/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class ButtonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelSong
     */
    public ButtonsPanel() {
        initComponents();
    }

    public void listen(ActionListener controller) {
        this.btnAdd.addActionListener(controller);
        this.btnReport.addActionListener(controller);
        this.btnDelete.addActionListener(controller);
        this.btnEdit.addActionListener(controller);
        this.btnClose.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background2.jpg"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addSong.png"))); // NOI18N
        btnAdd.setActionCommand("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editSong.png"))); // NOI18N
        btnEdit.setActionCommand("Edit");
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteSong.png"))); // NOI18N
        btnDelete.setActionCommand("Delete");
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reportOfSongs.png"))); // NOI18N
        btnReport.setActionCommand("Report");
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        btnClose.setActionCommand("Exit");
        add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
