/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import ucr.ac.cr.sisong.model.Artist;

/**
 *
 * @author sivv2
 */
public class DataPanelArtist extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelArtist
     */
    public DataPanelArtist() {
        initComponents();
    }

    public String getMusicalGenre() {
        return cbMusicalGenre.getSelectedItem().toString();
    }

    public void setMusicalGenre(String musicalGenre) {
        this.cbMusicalGenre.setSelectedItem(musicalGenre);
    }

    public String getNation() {
        return cbNation.getSelectedItem().toString();
    }

    public void setNation(String nation) {
        this.cbNation.setSelectedItem(nation);
    }

    public int getIdArtist() {
        return Integer.parseInt(lbIdArtist.getText());
    }

    public void setIdArtist(int id) {
        this.lbIdArtist.setText(Integer.toString(id));
    }

    public String getNameArtist() {
        return txtNameArtist.getText();
    }

    public void setNameArtist(String name) {
        this.txtNameArtist.setText(name);
    }

    public void clean() {
        this.lbIdArtist.setText("");
        this.txtNameArtist.setText("");
        this.cbMusicalGenre.setSelectedIndex(0);
        this.cbNation.setSelectedIndex(0);
    }

    public void setIDCombo(String[] idList) {
        this.cbIDArtist.setModel(new DefaultComboBoxModel<>(idList));
    }

    public String getIDCombo() {
        return this.cbIDArtist.getSelectedItem().toString();
    }

    public void listenComboID(ActionListener controller) {
        this.cbIDArtist.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNation = new javax.swing.JComboBox<>();
        cbMusicalGenre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNameArtist = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbIdArtist = new javax.swing.JLabel();
        cbIDArtist = new javax.swing.JComboBox<>();
        lbBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(356, 200));
        setPreferredSize(new java.awt.Dimension(356, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbNation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected option", "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania (Myanmar)", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guyana", "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", "República Democrática del Congo", "República Dominicana", "República Sudafricana", "Ruanda", "Rumania", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue" }));
        add(cbNation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        cbMusicalGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected option", "Rock", "Pop", "Hip-hop", "Rap", "Jazz", "Blues", "Reggae", "Country", "Electronic", "Folk", "Indie", "Metal", "Punk", "Funk", "Soul", "Gospel", "Classical", "Alternative", "Disco" }));
        add(cbMusicalGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 90, -1));

        jLabel3.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nation:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Musical genre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Artist registry");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txtNameArtist.setActionCommand("");
        add(txtNameArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, -1));

        jLabel2.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 30, 20));

        lbIdArtist.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        lbIdArtist.setForeground(new java.awt.Color(255, 255, 255));
        lbIdArtist.setText("0");
        lbIdArtist.setToolTipText("");
        add(lbIdArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 20));

        cbIDArtist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artists id" }));
        cbIDArtist.setActionCommand("comboIDArtist");
        add(cbIDArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        lbBackground.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ArtistBackground2.jpg"))); // NOI18N
        lbBackground.setText(" ");
        add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 200));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbIDArtist;
    private javax.swing.JComboBox<String> cbMusicalGenre;
    private javax.swing.JComboBox<String> cbNation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbIdArtist;
    private javax.swing.JTextField txtNameArtist;
    // End of variables declaration//GEN-END:variables
}
