/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sisong.view;
//******************************

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import ucr.ac.cr.sisong.model.Song;
//***********************************

/**
 *
 * @author Stephanie Venegas Villalobos C38405
 */
public class DataPanelSong extends javax.swing.JPanel {

    /**
     * Creates new form ButtonsPanel
     */
    public DataPanelSong() {
        initComponents();
    }

    public void setLbIdSong(int idSong) {
        this.lbIdSong.setText(String.valueOf(idSong));
    }// Cargar el ID en el label

    public Song getSong() {
        return new Song(Integer.parseInt(this.lbIdSong.getText()),
                this.txTitle.getText(),
                Double.parseDouble(this.spTime.getValue().toString()),
                this.cbMusicGenre.getSelectedItem().toString(),
                Integer.parseInt(this.spReleaseYear.getValue().toString()));
    }

    public void setSong(Song song) {
        this.lbIdSong.setText(String.valueOf(song.getIdSong()));
        this.txTitle.setText(song.getTitle());
        this.spTime.setValue(song.getTime());
        this.cbMusicGenre.setSelectedItem(song.getMusicGenre());
        this.spReleaseYear.setValue(2024);
    }

    public void clean() {
        this.lbIdSong.setText("");
        this.txTitle.setText("");
        this.spTime.setValue(0.1);
        this.cbMusicGenre.setSelectedIndex(0);
        this.spReleaseYear.setValue(2024);
    }

    public void setCbSong(String[] idSong) {
        DefaultComboBoxModel model = new DefaultComboBoxModel(idSong);
        model.insertElementAt("Selected Option", 0);
        this.cbSong.setModel(model);
    } 
    
    public void setCbMusicGenre(){
        this.cbMusicGenre.setModel(new DefaultComboBoxModel<>(new String[] {"Selected option","Pop", "Rock", "Metal", "Regueton", "Salsa", "Cumbia", "Clasica", "Hip-Hop", "Jazz", "Bachata", "Merengue"}));
    }

    public void listenCombo(ActionListener controller) {
        this.cbSong.addActionListener(controller);
    }

    public String getCbSong() {
        return this.cbSong.getSelectedItem().toString();
    }

    public void setEditCbCombo(boolean state) {
        this.cbSong.setEnabled(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        lbIdSong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spTime = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cbMusicGenre = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        spReleaseYear = new javax.swing.JSpinner();
        cbSong = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Song record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        JLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(0, 102, 102));
        JLabel2.setText("ID Song:");
        add(JLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, 20));

        lbIdSong.setText("0");
        add(lbIdSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 109, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Title:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 50, 20));
        add(txTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 109, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Duration:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        spTime.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.0d, null, 0.1d));
        add(spTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 109, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Music genre:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        add(cbMusicGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 109, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Release year:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        spReleaseYear.setModel(new javax.swing.SpinnerNumberModel(2024, 1582, 2024, 1));
        add(spReleaseYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 109, -1));

        cbSong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected Item" }));
        cbSong.setActionCommand("songCombo");
        cbSong.setEnabled(false);
        add(cbSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background2.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -10, 620, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel2;
    private javax.swing.JComboBox<String> cbMusicGenre;
    private javax.swing.JComboBox<String> cbSong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbIdSong;
    private javax.swing.JSpinner spReleaseYear;
    private javax.swing.JSpinner spTime;
    private javax.swing.JTextField txTitle;
    // End of variables declaration//GEN-END:variables
}
