/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import ucr.ac.cr.sisong.model.Artist;

/**
 *
 * @author Stephanie Venegas Villalobos C38405
 */
public class DataPanelArtist extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelArtist
     */
    public DataPanelArtist() {
        initComponents();
    }

    //String artistName, String musicalGenre, String nation, int id
    public Artist getArtist() {
        return new Artist(this.txtNameArtist.getText(),
                this.cbMusicalGenre.getSelectedItem().toString(),
                this.cbNation.getSelectedItem().toString());
    }

    public void setArtist(Artist artist) {
        this.txtNameArtist.setText(String.valueOf((artist.getArtistName())));
        this.cbMusicalGenre.setSelectedItem((artist.getMusicalGenre()));
        this.cbNation.setSelectedItem(artist.getNation());
    }

    public void clean() {

        this.txtNameArtist.setText("");
        this.cbMusicalGenre.setSelectedIndex(0);
        this.cbNation.setSelectedIndex(0);
        
    }

    public void setNameCombo(String[] idList) {
        this.cbArtistsName.setModel(new DefaultComboBoxModel<>(idList));
    }

    public String getNameCombo() {
        return this.cbArtistsName.getSelectedItem().toString();
    }

    public void listenComboName(ActionListener controller) {
        this.cbArtistsName.addActionListener(controller);
    }

    public void setCbNation() {
        this.cbNation.setModel(new DefaultComboBoxModel<>(new String[]{
            "Selected option",
            "Argentina",
            "Bolivia",
            "Brazil",
            "Canada",
            "Chile",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Dominican Republic",
            "Ecuador",
            "El Salvador",
            "Guatemala",
            "Haiti",
            "Honduras",
            "Jamaica",
            "Mexico",
            "Nicaragua",
            "Panama",
            "Paraguay",
            "Peru",
            "United States",
            "Uruguay",
            "Venezuela"
        }));
    }

    public void setCbMusicGenre() {
        this.cbMusicalGenre.setModel(new DefaultComboBoxModel<>(new String[]{"Selected option", "Pop", "Rock", "Metal", "Regueton", "Salsa", "Cumbia", "Clasica", "Hip-Hop", "Jazz", "Bachata", "Merengue"}));
    }

    public void setCbNameArtist(String[] vectorNames) {
        this.cbArtistsName.setModel(new DefaultComboBoxModel<>(vectorNames));
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNation = new javax.swing.JComboBox<>();
        cbMusicalGenre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNameArtist = new javax.swing.JTextField();
        cbArtistsName = new javax.swing.JComboBox<>();
        lbBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(450, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(cbNation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        add(cbMusicalGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, -1));

        jLabel3.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nation:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Musical genre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Artist registry");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txtNameArtist.setActionCommand("");
        add(txtNameArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 120, -1));

        cbArtistsName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artist Name" }));
        cbArtistsName.setToolTipText("");
        cbArtistsName.setActionCommand("cbNameArtist");
        add(cbArtistsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        lbBackground.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ArtistBackground2.jpg"))); // NOI18N
        lbBackground.setText(" ");
        add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 210));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbArtistsName;
    private javax.swing.JComboBox<String> cbMusicalGenre;
    private javax.swing.JComboBox<String> cbNation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JTextField txtNameArtist;
    // End of variables declaration//GEN-END:variables
}
