/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Stephanie Venegas Villalobos C38405
 */
public class GUIArtist extends javax.swing.JFrame {

    /**
     * Creates new form GUIArtist
     */
    public GUIArtist() {
        initComponents();
    }

    public ButtonsPanel getButtonsPanel() {
        return buttonsPanel2;
    }

    public DataPanelArtist getDataPanelArtist() {
        return dataPanelArtist2;
    }

    //ojo es el mismo de GUISong
    public void setMessage(String msj) {
        JOptionPane.showMessageDialog(this, msj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonsPanel2 = new ucr.ac.cr.sisong.view.ButtonsPanel();
        dataPanelArtist2 = new ucr.ac.cr.sisong.view.DataPanelArtist();

        setMinimumSize(new java.awt.Dimension(383, 372));
        setPreferredSize(new java.awt.Dimension(383, 372));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 40));
        getContentPane().add(buttonsPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 370, 80));

        dataPanelArtist2.setPreferredSize(new java.awt.Dimension(388, 297));
        getContentPane().add(dataPanelArtist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dataPanelArtist2.clean();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.sisong.view.ButtonsPanel buttonsPanel2;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
