/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Stephanie
 */
public class GUIMain extends javax.swing.JFrame {

    /**
     * Creates new form GUIAlbum
     */
    public GUIMain() {
        initComponents();
    }

    public void listen(ActionListener controller) {
        this.jmiExit.addActionListener(controller);
        this.jmiArtist.addActionListener(controller);
        this.jmiAlbums.addActionListener(controller);
        this.jmiSongs.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiSongs = new javax.swing.JMenuItem();
        jmiArtist = new javax.swing.JMenuItem();
        jmiAlbums = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jmiExit.setText("Exit");
        jmiExit.setToolTipText("");
        jMenu1.add(jmiExit);

        jMenuItem2.setText("Credits");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jmiSongs.setText("Songs");
        jmiSongs.setToolTipText("");
        jMenu2.add(jmiSongs);

        jmiArtist.setText("Artist");
        jMenu2.add(jmiArtist);

        jmiAlbums.setText("Albums");
        jmiAlbums.setToolTipText("");
        jmiAlbums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlbumsActionPerformed(evt);
            }
        });
        jMenu2.add(jmiAlbums);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlbumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAlbumsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmiAlbums;
    private javax.swing.JMenuItem jmiArtist;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiSongs;
    // End of variables declaration//GEN-END:variables
}
